In [ ]:
#Geethika Kanna
#Guided_Assignment_220810

In [ ]:
'''
Numpy Assignments
Write a code that takes in a number x from the user and creates a 1x20 array with random numbers ranging from 0 to x
Write a code that creates a 4x5 array in which numbers ranging between 300 and 500 such that the difference between elements is 10
Write a code that creates a 20x20 numpy array of random values that ranges from -1000 to 1000 and obtain the maximum, minimum, and mean values
In the following matrix, replace the last row with -1 Multiply the 2x2 matrix in the upper right corner by 2 X = [2 30 20 -2 -4] [3 4 40 -3 -2] [-3 4 -6 90 10] [25 45 34 22 12] [13 24 22 32 37]
In the following matrix, replace negative elements by 0 and replace odd elements with 25 X = [2 30 20 -2 -4] [3 4 40 -3 -2] [-3 4 -6 90 10] [25 45 34 22 12] [13 24 22 32 37]
'''

In [ ]:
import numpy as np

In [ ]:
#Assignment1

x = int(input())
arr = np.random.randint(0,x,(1,20))
print('Array of size 1x20 with random numbers ranging from 0 to',x)
print(arr)

8
Array of size 1x20 with random numbers ranging from 0 to 8
[[3 6 5 0 5 1 5 6 6 3 4 0 5 1 7 7 5 0 2 6]]


In [ ]:
#Assignment2

arr = np.arange(300,500,10)
arr1 = arr.reshape(4,5)
print('Array of size 4x5 in which numbers ranging between 300 and 500 and the difference between elements is 10')
print(arr1)

Array of size 4x5 in which numbers ranging between 300 and 500 and the difference between elements is 10
[[300 310 320 330 340]
 [350 360 370 380 390]
 [400 410 420 430 440]
 [450 460 470 480 490]]


In [ ]:
#Assignment3

arr = np.random.randint(-1000,1000,(20,20))
print('Array of size 20x20 having random values that ranges from -1000 to 1000')
print(arr)
print('maximum value:',np.max(arr))
print('minimum value:',np.min(arr))
print('mean value:',np.mean(arr))

Array of size 20x20 having random values that ranges from -1000 to 1000
[[-998 -284 -320  570  792  344 -965 -769  592 -685 -783  352 -528  171
   564  963  459 -728  183 -994]
 [ 349 -304 -338  379 -808 -524  922  673  426 -933 -850 -489 -174 -352
   292  383 -388  239 -856  448]
 [-167 -708 -483 -513 -539 -761 -981  -10  415 -956  521  800  836  869
  -637  959   46 -633 -239 -745]
 [ 515  943   18  345  847  534 -836 -629 -896  352  753 -540  825 -865
  -807  255 -201  533  128 -998]
 [ 216 -814  359 -851 -967  611  757 -489 -415 -270   49  503 -729  616
   183  773 -725 -305 -637  -31]
 [-510  102 -242 -514 -509  508  100 -536  595  791  157   10  995 -507
   533  501  543 -869  896  321]
 [-171  727 -384 -543 -289  382  763  -38 -643  157 -517 -246 -637  104
   421  503 -200 -303 -450 -983]
 [ 104   40  -84 -630  838 -263 -691 -623  593  817 -878  686  570 -115
   659  839   97  592 -313 -303]
 [ 539  779  540 -108 -316  899  796  861  779 -913 -111 -471 -757 -106
   -67  803 -746

In [ ]:
#Assignment4

X =np.array([[2,30,20,-2,-4], 
[3, 4, 40, -3, -2], 
[-3, 4, -6, 90, 10],
[25, 45, 34, 22, 12],
[13, 24, 22, 32, 37]])
X[4]=-1
print('Array after replacing last row with -1')
print(X)
print('After multiplication of 2x2 matrix in the upper right corner by 2')
print(X[:2,3:]*2)

Array after replacing last row with -1
[[ 2 30 20 -2 -4]
 [ 3  4 40 -3 -2]
 [-3  4 -6 90 10]
 [25 45 34 22 12]
 [-1 -1 -1 -1 -1]]
After multiplication of 2x2 matrix in the upper right corner by 2
[[-4 -8]
 [-6 -4]]


In [ ]:
#Assignment5

X =np.array([[2,30,20,-2,-4],[3,4,40,-3,-2], [-3, 4, -6, 90, 10], [25, 45, 34, 22, 12], [13, 24, 22, 32, 37]])
X1=np.where(X<0, 0, X)
print('Array after replacing negative elements by 0')
print(X1)
X2=np.where(X%2!=0, 25, X)
print('Array after replacing odd elements with 25')
print(X2)
X2=np.where(X%2!=0, 25, X1)
print('Array after replacing both negative elements by 0 and odd elements with 25')
print(X2)

Array after replacing negative elements by 0
[[ 2 30 20  0  0]
 [ 3  4 40  0  0]
 [ 0  4  0 90 10]
 [25 45 34 22 12]
 [13 24 22 32 37]]
Array after replacing odd elements with 25
[[ 2 30 20 -2 -4]
 [25  4 40 25 -2]
 [25  4 -6 90 10]
 [25 25 34 22 12]
 [25 24 22 32 25]]
Array after replacing both negative elements by 0 and odd elements with 25
[[ 2 30 20  0  0]
 [25  4 40 25  0]
 [25  4  0 90 10]
 [25 25 34 22 12]
 [25 24 22 32 25]]
